name: CI ClinicaAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4

    - name: Instalar .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependencias proyecto principal
      run: dotnet restore ClinicaAPI/ClinicaAPI.csproj

    - name: Restaurar dependencias proyecto de pruebas
      run: dotnet restore ClinicaAPI.Tests/ClinicaAPI.Tests.csproj

    - name: Compilar proyecto principal
      run: dotnet build ClinicaAPI/ClinicaAPI.csproj --no-restore --configuration Release

    - name: Ejecutar pruebas unitarias
      run: dotnet test ClinicaAPI.Tests/ClinicaAPI.Tests.csproj --no-build --verbosity normal